SET NAMES UTF8;
DROP DATABASE IF EXISTS `know`;
CREATE DATABASE `know` DEFAULT CHARACTER SET UTF8;
USE `know`;




CREATE TABLE `know`(
    `id` INT PRIMARY KEY AUTO_INCREMENT,    
    `knlg` VARCHAR(5000),
    `pid` INT,
    `path` VARCHAR(1000)
)DEFAULT CHARACTER SET UTF8 COMMENT "知识";

INSERT INTO `know` VALUES(NULL,'知识',0,'0-1');   
INSERT INTO `know` VALUES(NULL,'结构',1,'0-1-2');
INSERT INTO `know` VALUES(NULL,'建筑',1,'0-1-3');
INSERT INTO `know` VALUES(NULL,'工序',3,'0-1-3-4');



